ietf-wg-webtrans/draft-ietf-webtrans-http3

- draft-ietf-webtrans-http3.md
> Support buffering for streams on both sides.

- draft-ietf-webtrans-http3.md
This matches agreement at the last interim.  We should separate this
into a different draft, but for now this will make the draft match
implementation.
> Redefine server-initiated bidi streams

- draft-ietf-webtrans-http3.md
> Close connection on an invalid session ID received.

- draft-ietf-webtrans-http3.md
This PR keeps WebTransport in sync with the latest changes in draft-ietf-masque-h3-datagram.
> Keep track of latest changes in HTTP Datagrams

- draft-ietf-webtrans-http3.md
> clarify when the client can open streams and send datagrams

- draft-ietf-webtrans-http3.md
> Add recommendation text for throttling

- draft-ietf-webtrans-http3.md
> Clarify SETTINGS behavior for 0-RTT

- draft-ietf-webtrans-http3.md
> Require sending SETTINGS_ENABLE_CONNECT_PROTOCOL

- draft-ietf-webtrans-http3.md
> Add a capsule to drain a WebTransport session

- draft-ietf-webtrans-http3.md
> Allow STOP_SENDING with CLOSE_WEBTRANSPORT_SESSION

- draft-ietf-webtrans-http3.md
Require SETTINGS_H3_DATAGRAM and max_datagram_frame_size TP
Closes #84
> Require SETTINGS_H3_DATAGRAM and max_datagram_frame_size TP

- draft-ietf-webtrans-http3.md
Fix up references to setting names
Fixes #108
> Fix up references to setting names

- draft-ietf-webtrans-http3.md
> Discuss redirect handling

- draft-ietf-webtrans-http3.md
> Make capsule protocol usage more explicit

- draft-ietf-webtrans-http3.md
Note the source of quarter stream ID
Closes #110
> Note the source of quarter stream ID

- draft-ietf-webtrans-http3.md
Replace SETTINGS_ENABLE_WEBTRANSPORT with SETTINGS_WEBTRANSPORT_MAX_SESSIONS
Fixes #125
> Replace SETTINGS_ENABLE_WEBTRANSPORT with SETTINGS_WEBTRANSPORT_MAX_SESSIONS

- draft-ietf-webtrans-http3.md
This is me, racing @vasilvv...
Closes #126.
> Redo GOAWAY and DRAIN_...long name

- draft-ietf-webtrans-http3.md
> Explain how Priority interacts with WebTransport sessions

- draft-ietf-webtrans-http3.md
> Capsules are not a WebTransport feature

- draft-ietf-webtrans-http3.md
> don't require the client to send SETTINGS_ENABLE_CONNECT_PROTOCOL

- draft-ietf-webtrans-http3.md
> Define key exporters

- draft-ietf-webtrans-http3.md
> Don't rely on ACKs for session closure

- draft-ietf-webtrans-http3.md
> Make WebTransport resets reliable

- draft-ietf-webtrans-http3.md
I'm not 100% sure about the change from:
"If at any point a session ID is received that cannot a valid ID for a"
to
"If at any point a session ID is received that cannot be a valid ID for a"
So please double check that logic. I went with the smallest hamming distance.
> Fix some typos

- draft-ietf-webtrans-http3.md
> WebTransport requests are malformed if the settings are wrong

- .github/workflows/archive.yml
- .github/workflows/ghpages.yml
- .github/workflows/publish.yml
- .github/workflows/update.yml
Update upload-artifact actions
> Update upload-artifact actions

- draft-ietf-webtrans-http3.md
> Clarify GOAWAY

- draft-ietf-webtrans-http3.md
> The obvious preference order

- draft-ietf-webtrans-http3.md
> Clarify which streams FIN / RESET during termination

- draft-ietf-webtrans-http3.md
> Explain how WT_DRAIN_SESSION can be used for fun and profit

- draft-ietf-webtrans-http3.md
> specify error code for STOP_SENDING frame sent on the CONNECT stream

- draft-ietf-webtrans-http3.md
> Prefer RFC 9220 instead of RFC 8441 when talking about extended CONNECT for H3

- draft-ietf-webtrans-http3.md
> Condense sections 3.1 and 3.2

- draft-ietf-webtrans-http3.md
Rename WEBTRANSPORT -> WT
Fixes #202
> Rename WEBTRANSPORT -> WT

- draft-ietf-webtrans-http3.md
Add negotiation of flow control, client sends SETTINGS again
Fixes #150
> Add negotiation of flow control, client sends SETTINGS again
