draft-vvv-webtransport-http3.md, draft-vvv-webtransport-overview.md, draft-vvv-webtransport-quic.md
This defines a new URL scheme for QuicTransport, and clarifies the use
of "https" for Http3Transport.
=> Add a URL scheme requirement

draft-vvv-webtransport-quic.md
We currently use 16-bit integers for header names.  There probably won't
ever be more than 65,000 headers, but this does not let users add their
own custom headers easily.  Thus, this commit changes uint16 to string.
We currently provide a way for a server to explicitly reject client's
origin, but no way to explicitly accept it.  This commit solves this by
turning the client indication stream into a bidirectional handshake
stream.  Server confirms the handshake by sending a FIN on its end of
the handshake stream.
=> Refactor client indication into a full header exchange

draft-vvv-webtransport-http3.md
This replaces a distinct Session ID mechanism with using stream ID of
the CONNECT stream as a Session ID.
The transport parameter used to opt into WebTransport is replaced with
a SETTINGS value.
=> Update WebTransport over HTTP/3 to be more in sync with HTTP/2

draft-ietf-webtrans-http3.md
Requires the server to defer the processing of any incoming WebTransport
sessions until the relevant settings have been received from the client.
This makes versioning WebTransport extension possible.
Fixes #39.
=> Require the server to wait for SETTINGS

draft-ietf-webtrans-http3.md
=> Allocate HTTP/3 error codes for use by the WebTransport application

draft-ietf-webtrans-http3.md
This requirement has been irrelevant since quicwg/base-drafts#2773
=> Remove the text about initial_max_bidi_streams

draft-ietf-webtrans-http3.md
This makes our behavior consistent with the regular CONNECT method.
Fixes #42.
=> Replace 200 status code with 2xx

draft-ietf-webtrans-http3.md
=> Add a mechanism to close a session with an error message

draft-ietf-webtrans-http3.md
This PR updates draft-ietf-webtrans-http3 to account for the MASQUE HTTP Datagram Design Team changes that landed in draft-ietf-masque-h3-datagram-06.
Fixes #54.
=> Update to draft-ietf-masque-h3-datagram-06

draft-ietf-webtrans-http3.md
- s/an WebTransport/a WebTransport
- spellings
=> Spelling and grammar nits

draft-ietf-webtrans-http3.md
Capsule design team output. Minimal changes to HTTP/3, which was already using capsules and is now joined by [HTTP/2](https://github.com/ietf-wg-webtrans/draft-webtransport-http2/pull/58).
Same content as [draft PR](), thank you to those who have already reviewed!
Closes #22
Closes #34 
Closes #66
=> Capsule design team output [HTTP/3]

draft-ietf-webtrans-http3.md
This is vaguely based on the similar text in the WebSocket RFC.
Fixes #92.
=> Relax the Origin header requirement

draft-ietf-webtrans-http3.md
Also ban sending it anywhere that's not the beginning of the stream.
Fixes #71
Potentially also fixes #48 and #81
=> Clarify the nature of WEBTRANSPORT_STREAM

draft-ietf-webtrans-http3.md
This updates the IANA considerations section for Frame Type to match https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-04#section-4.2, by including "server-initiated" in the type of bidirectional streams allowed by the `WEBTRANSPORT_STREAM` frame.
=> Clarify Frame Type Registration section

draft-ietf-webtrans-http3.md
In https://github.com/web-platform-tests/wpt/pull/38782, it was suggested that 403 status code should be used when Origin verification fails.
=> Clarify status code for Origin verification

draft-ietf-webtrans-http3.md
This is mostly based on what Chrome currently does in production.
Fixes #89.
=> Document how to close both the session and the underlying connection

draft-ietf-webtrans-http3.md
By switching from Frames to special signal values at byte position 0,
we are really extending HTTP/3 rules. So this is an attempt to paint
that out more cleanly and tidy up some loose ends or stale text in the
draft.
The outcome is that we make it clear that WebTransport streams never use
frames. Instead, they are always a sequence of some preamble at the
start of a stream, followed by a session ID, followed by user-specified
stream data. This makes it more obvious that endpoints should never send
0x41 such that the peer could interpret it as being a frame on any
frame-bearing stream (like the control stream). If you understand
WebTransport but didn't enable it, then receiving 0x41 is also bad, so
blow up.
=> Expand on HTTP/3 extension aspects

draft-ietf-webtrans-http3.md
I am picking floor() here, since `//` can be confused with a C-style comment.
=> Be consistent about how we spell out integer divsion

draft-ietf-webtrans-http3.md
=> Extend the error space for reset codes to 32 bits

draft-ietf-webtrans-http3.md
This change is editorial. It is not intended to redefine how the error
codes operate but instead clarify their usage and make them more
consistent with how HTTP/3 and QUIC do things.
So, we drop `H3` prefix from the error codes, because this is all about
WebTransport.
Then we make a single label - WEBTRANSPORT_APPLICATION_ERROR - that
covers the entire range of codes that we care about. This is similar to
how QUIC's CRYPTO_ERROR works. And in the part we talk about mapping,
add a little callout to the label similar to https://datatracker.ietf.org/doc/html/rfc9001#section-4.8
Fixes #117
=> Tweak how HTTP/3 error codes are presented for use

draft-ietf-webtrans-http3.md
In a previous PR, I said that I bumped a SETTINGS parameter number to indicate the new draft version.  Turns out, I accidentally changed the WEBTRANSPORT_MAX_SESSIONS codepoint instead.
This PR actually changes the correct one (ENABLE_WEBTRANSPORT). It also replaces "draft-06" with "draft-07", since draft-06 is not really implementable at this state.
=> Redo the version bump

draft-ietf-webtrans-http3.md
=> Add subprotocol negotiation

draft-ietf-webtrans-http3.md
Adjust SETTINGS, buffering requirements, waiting for session establishment
As discussed: 
- Client MUST wait for server settings
- Endpoints MUST send SETTINGS_H3_DATAGRAM (however servers that want to validate this MUST need to take into account the fact that the request might arrive before the client's SETTINGS)
- Client no longer sends the WEBTRANSPORT_MAX_SESSIONS setting
- Add a "Considerations for future versions of WebTransport" section that explain that if a future version of WebTransport changes the syntax of the request, it'll need to change the Upgrade Token. Similarly, changes to stream formats will require changes to the Unidirectional Stream Type and Bidirectional Stream Signal Value.
Fixes #135, #140, #141, and #143
=> Adjust SETTINGS, buffering requirements, waiting for session establishment

draft-ietf-webtrans-http3.md
It's true that you might not be able to close the stream in response (particularly if the close might indicate success where there was no actual response).  So allow either.
Closes #156.
=> A close can be followed by a close or reset

draft-ietf-webtrans-http3.md, package.json
Bernards commits
- Relationship between WebTransport, HTTP/3 and QUIC
- Update draft-ietf-webtrans-http3.md
- Update draft-ietf-webtrans-http3.md
- Update draft-ietf-webtrans-http3.md
My suggestions on top
https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/146/commits/05f31d55727611c35747146d10d7b3af93b20898
=> Relationship between WebTransport, HTTP/3 and QUIC

draft-ietf-webtrans-http3.md
1. The names of these fields was too much for poor little me.
2. Say that -Options is in preference order.
3. Remove a comma.
Closes #159.
=> Editorial changes for the subprotocol negotiation

draft-ietf-webtrans-http3.md
Finish rename of subprotocol -> protocol
Updating to be consistent everywhere with terminology, this now matches across HTTP/3, HTTP/2, and the overview document.
Closes #173.
=> Finish rename of subprotocol -> protocol

draft-ietf-webtrans-http3.md
Clarify that the CONNECT stream isn't included in the per-session stream flow control limits.
Fixes #176
=> Clarify that the CONNECT stream isn't included in the per-session stream flow control limits

draft-ietf-webtrans-http3.md
Updates `HTTP_REQUEST_REJECTED` to `H3_REQUEST_REJECTED` and adds the correct reference for the HTTP/3 error codes.
=> Replace HTTP_REQUEST_REJECTED with H3_REQUEST_REJECTED

draft-ietf-webtrans-http3.md
Rename DRAIN_WEBTRANSPORT_SESSION to WT_DRAIN_SESSION and CLOSE_WEBTRANSPORT_SESSION to WT_CLOSE_SESSION
Fixes #193
=> Rename DRAIN_WEBTRANSPORT_SESSION to WT_DRAIN_SESSION and CLOSE_WEBTRANSPORT_SESSION to WT_CLOSE_SESSION

draft-ietf-webtrans-http3.md
This does not modify HTTP/3 rules indicating that HTTP clients cannot send new requests with a stream ID greater or equal to the one in GOAWAY.
Fixes: #190
=> Clarify GOAWAY allows only new WebTransport streams

draft-ietf-webtrans-http3.md
Align on terminology for application vs. endpoint
Also took the opportunity to do an editorial pass.
Generally, this is fairly editorial, although there are a few changes to normative text -- they're not intended to change the meaning, but please do double check.
Fixes #191
=> Align on terminology for application vs. endpoint

draft-ietf-webtrans-http3.md
Borrowed language from RFC 9000 section 4.5 and adapted to WebTransport.
Fixes: #179
=> Clarify the use of final size
